from __future__ import annotations

import io
import json
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from .multitenant_e2e import (
    APIClient,
    E2EFailure,
    EXACT_QWEN_ASR_NAME,
    EXACT_QWEN_VLM_NAME,
    JsonlRecorder,
    TenantProvisioner,
    VariantFactory,
    classify_span,
    metrics_delta,
    parse_prometheus_stage_metrics,
)


class MultiTenantMetricTests(unittest.TestCase):
    def test_parse_and_delta_stage_metrics(self) -> None:
        before = parse_prometheus_stage_metrics(
            'weknora_document_stage_executions_total{outcome="success",stage="wiki"} 2\n'
            'weknora_document_stage_executions_total{outcome="error",stage="wiki"} 1\n'
        )
        after = parse_prometheus_stage_metrics(
            'weknora_document_stage_executions_total{outcome="success",stage="wiki"} 7\n'
            'weknora_document_stage_executions_total{outcome="error",stage="wiki"} 1\n'
        )
        self.assertEqual(before["wiki:success"], 2)
        self.assertEqual(
            metrics_delta({"worker-a": before}, {"worker-a": after}),
            {"worker-a": {"wiki:success": 5.0}},
        )

    def test_classify_span_uses_task_metadata(self) -> None:
        self.assertEqual(classify_span({"name": "embedding"}), "embedding")
        self.assertEqual(
            classify_span(
                {
                    "name": "anything",
                    "metadata": {"executor_task_type": "question:generation"},
                }
            ),
            "questions",
        )
        self.assertEqual(classify_span({"name": "unrelated"}), "")


def _minimal_docx(path: Path) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "[Content_Types].xml",
            (
                '<?xml version="1.0"?>'
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                '<Default Extension="xml" ContentType="application/xml"/>'
                "</Types>"
            ),
        )
        archive.writestr(
            "word/document.xml",
            (
                '<?xml version="1.0"?>'
                '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
                "<w:body><w:p><w:r><w:t>seed</w:t></w:r></w:p></w:body></w:document>"
            ),
        )


class VariantFactoryTests(unittest.TestCase):
    def test_variants_are_unique_and_keep_valid_docx_container(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            files = []
            for index in range(20):
                extension = "docx" if index == 1 else "txt"
                name = f"seed-{index}.{extension}"
                path = root / name
                if extension == "docx":
                    _minimal_docx(path)
                else:
                    path.write_text(f"seed {index}", encoding="utf-8")
                files.append({"filename": name, "extension": extension})
            (root / "manifest.json").write_text(
                json.dumps({"files": files}),
                encoding="utf-8",
            )
            factory = VariantFactory(root, small_kib=1, medium_kib=2, large_kib=3)
            first = factory.build(0, "test")
            second = factory.build(20, "test")
            docx = factory.build(1, "test")

            self.assertNotEqual(first.marker, second.marker)
            self.assertNotEqual(first.content, second.content)
            self.assertTrue(first.content_unique)
            # Exercise that generated bytes can be opened as an OOXML ZIP,
            # not merely that the filename still ends in .docx.
            with zipfile.ZipFile(io.BytesIO(docx.content), "r") as archive:
                document = archive.read("word/document.xml")
            self.assertIn(docx.marker.encode(), document)


class _ProvisionAdmin:
    base_url = "http://unit.test"
    timeout = 1.0

    def __init__(self) -> None:
        self.calls: list[tuple[str, str]] = []

    def request(self, method: str, path: str, **_: object) -> object:
        self.calls.append((method, path))
        if method == "POST" and path == "/api/v1/custom/admin/users":
            return {"user": {"id": "user-1", "tenant_id": 12345}}
        if method == "POST" and path == "/api/v1/tenants/12345/api-key":
            return {"api_key": "ephemeral-test-key"}
        return {}


class _GrantFailureProvisioner(TenantProvisioner):
    def _grant_exact_chat(self, user_id: str) -> None:
        raise E2EFailure(f"grant failed for {user_id}")


class _ProvisionWithoutRemoteModels(TenantProvisioner):
    def _grant_exact_chat(self, user_id: str) -> None:
        return

    def _wait_models(self, client: object, timeout: float = 90.0) -> object:
        return type(
            "Models",
            (),
            {
                "chat_id": "chat",
                "embedding_id": "embedding",
                "vlm_id": "vlm",
                "asr_id": "asr",
                "chat_name": "deepseek-v4-flash-int8",
                "chat_base_url": "http://litellm:14000",
            },
        )()


class TenantProvisionerCleanupTests(unittest.TestCase):
    def test_generated_local_account_username_contains_no_run_id_punctuation(self) -> None:
        class Admin(_ProvisionAdmin):
            def request(self, method: str, path: str, **kwargs: object) -> object:
                if method == "POST" and path == "/api/v1/custom/admin/users":
                    body = kwargs.get("json_body")
                    assert isinstance(body, dict)
                    self.username = str(body["username"])
                return super().request(method, path, **kwargs)

        with tempfile.TemporaryDirectory() as raw:
            admin = Admin()
            provisioner = TenantProvisioner(
                admin,  # type: ignore[arg-type]
                JsonlRecorder(Path(raw) / "events.jsonl"),
            )
            provisioner._create_account(3, "dual-real-20260724-233733-a1b2c3")

            self.assertRegex(admin.username, r"^[A-Za-z0-9]{2,20}$")
            self.assertNotIn("-", admin.username)

    def test_partial_account_is_cleaned_when_model_grant_fails(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            admin = _ProvisionAdmin()
            provisioner = _GrantFailureProvisioner(
                admin,  # type: ignore[arg-type]
                JsonlRecorder(Path(raw) / "events.jsonl"),
            )

            with self.assertRaisesRegex(E2EFailure, "grant failed"):
                provisioner.provision(
                    principal_count=1,
                    knowledge_bases_per_principal=2,
                    run_suffix="unit-test",
                )

            self.assertIn(("DELETE", "/api/v1/tenants/12345"), admin.calls)
            self.assertIn(
                ("PUT", "/api/v1/custom/admin/users/user-1/active"),
                admin.calls,
            )

    def test_required_qwen_models_never_fall_back(self) -> None:
        models = [
            {"id": "omni", "name": "/models/Qwen2.5-Omni-7B", "type": "VLLM"},
            {"id": "sense", "name": "FunAudioLLM/SenseVoiceSmall", "type": "ASR"},
        ]
        with self.assertRaisesRegex(E2EFailure, "Qwen3-VL-32B-Instruct"):
            TenantProvisioner._require_exact_model(
                models, "vllm", EXACT_QWEN_VLM_NAME
            )
        with self.assertRaisesRegex(E2EFailure, "Qwen3-ASR-1.7B"):
            TenantProvisioner._require_exact_model(
                models, "asr", EXACT_QWEN_ASR_NAME
            )

    def test_real_non_audio_corpus_keeps_exact_asr_binding_but_disables_calls(self) -> None:
        models = type(
            "Models",
            (),
            {
                "chat_id": "chat",
                "embedding_id": "embedding",
                "vlm_id": "vlm",
                "asr_id": "qwen-asr",
            },
        )()
        body = TenantProvisioner._kb_body(
            "公司制度",
            models,  # type: ignore[arg-type]
            asr_enabled=False,
            wiki_ingest_batch_size=20,
            wiki_ingest_map_parallel=4,
            wiki_ingest_reduce_parallel=4,
        )

        self.assertEqual(body["asr_config"]["model_id"], "qwen-asr")
        self.assertFalse(body["asr_config"]["enabled"])
        self.assertEqual(body["wiki_config"]["ingest_batch_size"], 20)
        self.assertEqual(body["wiki_config"]["ingest_map_parallel"], 4)
        self.assertEqual(body["wiki_config"]["ingest_reduce_parallel"], 4)

    def test_provision_accepts_real_corpus_kb_name_and_tuning(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            admin = _ProvisionAdmin()
            provisioner = _ProvisionWithoutRemoteModels(
                admin,  # type: ignore[arg-type]
                JsonlRecorder(Path(raw) / "events.jsonl"),
            )
            created: dict[str, object] = {}

            def client_request(
                _client: object,
                method: str,
                path: str,
                **kwargs: object,
            ) -> object:
                self.assertEqual((method, path), ("POST", "/api/v1/knowledge-bases"))
                body = kwargs.get("json_body")
                self.assertIsInstance(body, dict)
                created.update(body)  # type: ignore[arg-type]
                return {"id": "kb-1", "summary_model_id": "chat"}

            with patch.object(APIClient, "request", new=client_request):
                principals = provisioner.provision(
                    principal_count=1,
                    knowledge_bases_per_principal=1,
                    run_suffix="real-corpus",
                    knowledge_base_name_factory=lambda _principal, _kb: "数据资料",
                    knowledge_base_body_kwargs={
                        "asr_enabled": False,
                        "wiki_ingest_batch_size": 20,
                    },
                )

            self.assertEqual(principals[0].knowledge_base_ids, ["kb-1"])
            self.assertEqual(created["name"], "数据资料")
            self.assertFalse(created["asr_config"]["enabled"])  # type: ignore[index]
            self.assertEqual(created["wiki_config"]["ingest_batch_size"], 20)  # type: ignore[index]


if __name__ == "__main__":
    unittest.main()
