// Package wikillm classifies Wiki model failures by durable scheduling
// semantics. It gives typed admission/provider errors priority over a nested
// HTTP status so an intermediary 403 cannot be mistaken for bad prompt data.
package wikillm

import (
	"context"
	"strings"

	"github.com/Tencent/WeKnora/internal/custom/modules/modeladmission"
	"github.com/Tencent/WeKnora/internal/models/chat"
)

type Class string

const (
	ClassUnknown           Class = "unknown"
	ClassCancelled         Class = "cancelled"
	ClassProviderTransient Class = "provider_transient"
	ClassProviderPermanent Class = "provider_permanent"
	ClassContract          Class = "contract_or_application"
)

func Classify(ctx context.Context, err error) Class {
	if err == nil {
		return ClassUnknown
	}
	if ctx != nil && ctx.Err() != nil {
		return ClassCancelled
	}
	// Check the outer typed wrapper first. A gateway/WAF 403 is deliberately
	// wrapped as ProviderUnavailableError by model admission; inspecting the
	// inner HTTP status first loses that stronger fact.
	if modeladmission.IsProviderUnavailable(err) ||
		modeladmission.IsModelWorkDeferred(err) {
		return ClassProviderTransient
	}
	if status, ok := chat.HTTPStatusCode(err); ok {
		switch {
		case status == 408 || status == 429 || status >= 500:
			return ClassProviderTransient
		case status == 403 && looksLikeIntermediaryHTML(err.Error()):
			return ClassProviderTransient
		case status >= 400 && status < 500:
			return ClassProviderPermanent
		}
	}
	message := strings.ToLower(err.Error())
	for _, marker := range []string{
		"status 408", "status 429", "status 500", "status 501",
		"status 502", "status 503", "status 504", "status 520",
		"status 521", "status 522", "status 523", "status 524",
	} {
		if strings.Contains(message, marker) {
			return ClassProviderTransient
		}
	}
	if strings.Contains(message, "status 403") && looksLikeIntermediaryHTML(message) {
		return ClassProviderTransient
	}
	for _, marker := range []string{
		"timeout", "timed out", "connection reset", "connection refused",
		"broken pipe", "no such host", "i/o timeout", "unexpected eof",
		"tls handshake", "context deadline exceeded",
	} {
		if strings.Contains(message, marker) {
			return ClassProviderTransient
		}
	}
	for _, marker := range []string{
		"status 400", "status 401", "status 403", "status 404",
		"unauthorized", "authentication failed", "model not found",
	} {
		if strings.Contains(message, marker) {
			return ClassProviderPermanent
		}
	}
	return ClassContract
}

func IsTransient(ctx context.Context, err error) bool {
	return Classify(ctx, err) == ClassProviderTransient
}

func IsPermanentProviderFault(ctx context.Context, err error) bool {
	return Classify(ctx, err) == ClassProviderPermanent
}

func looksLikeIntermediaryHTML(message string) bool {
	message = strings.ToLower(message)
	for _, marker := range []string{
		"<!doctype html", "<html", "</html>", "cloudfront",
		"request could not be satisfied", "generated by cloudfront",
		"error code 403",
	} {
		if strings.Contains(message, marker) {
			return true
		}
	}
	return false
}
